apiVersion: v1
kind: Endpoints
metadata:
  # the name here should match the name of the Service
  name: service-test
subsets:
  - addresses:
      - ip: 172.17.0.4 
      - ip: 172.17.0.5
      - ip: 172.17.0.2
    ports:
      - port: 80