apiVersion: v1
kind: Service
metadata:
  name: nodeport-nginx
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: nodeport 
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000