apiVersion: v1
kind: Service
metadata:
  name: nodeport-web
  namespace: default
spec:
  selector:
    type: default
  type: NodePort
  ports:
  - name: nodeport 
    protocol: TCP
    port: 80
    targetPort: 80