apiVersion: v1
kind: Service
metadata:
  name: service-web
  namespace: default
spec:
  selector:
    app: web-ubuntu
  ports:
  - name: service-clusterip
    protocol: TCP
    port: 80
    targetPort: 8080
    