apiVersion: apps/v1
kind: Deployment
metadata:
  name:  web-deployment
  namespace: default
  labels:
    tag:  web-app
spec:
  selector: 
    matchLabels:
      app: web-app
  replicas: 3

  template:
    metadata:
      labels:
        app:  web-app
    spec:
      containers:
      - name:  web-app
        image: pato2819/web-httpd-ubuntu:1.0
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        
        ports:
        - containerPort:  80
          name:  web-app
        