apiVersion: v1
kind: Service
metadata:
  name: nodeport-web
  namespace: default
spec:
  selector:
    tag: web-app
  type: NodePort
  ports:
  - name: nodeport 
    protocol: TCP
    port: 8080
    targetPort: 80