apiVersion: apps/v1
kind: Deployment
metadata:
  name:  web-deployment
  namespace: default
  labels:
    app:  default
spec:
  selector: 
    matchLabels:
      app: default
  replicas: 4

  template:
    metadata:
      labels:
        app:  default
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  web-app
        image: pato2819/web-httpd-ubuntu:1.0
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        
        ports:
        - containerPort:  80
          name:  web-app
        