apiVersion: v1
kind: Pod
metadata:
  name: "mongodb-web"
  namespace: default
  labels:
    app: "mongodb-web"
spec:
  containers:
  - name: mongodb 
    image: "mongo"
    ports:
    - containerPort:  27017
      name:  db 
    env:
      - name: root-username
        valueFrom:
          secretKeyRef:
            name: thirdsecret 
            key: MONGO_INITDB_ROOT_USERNAME
      - name: root-password
        valueFrom:
          secretKeyRef:
            name: thirdsecret 
            key: MONGO_INITDB_ROOT_PASSWORD
