apiVersion: v1
kind: Pod
metadata:
  name: "mongodb-web"
  namespace: default
  labels:
    app: "mongodb-web"
spec:
  containers:
  - name: mongodb 
    image: "mongo"
    ports:
    - containerPort:  27017
      name:  db 
    volumeMounts:
    - name: foo
      mountPath: /etc/foo
      readOnly: true 
  volumes:
    - name: foo
      secret:
        secretName: thirdsecret 

