apiVersion: v1
kind: Pod
metadata:
  name: mydatabase
spec:
  containers:
  - name: mongodb
    image: mongo 
    env:
      - MONGO_INITDB_ROOT_USERNAME: example
        MONGO_INITDB_ROOT_PASSWORD: micontraseña
    ports:
    - containerPort: 27017